### ISSUE TITLE
how to debug this project in vscode ?

### ISSUE THREAD

**Issue by KevinBaiSg** [harryho/react-crm#1]

**Comment by harryho** [comment]
I recommended the extension tool of react, redux for chrome, since it is not a back end node app or SSR app. I don't see the benefit there. I believe stackoverflow or Google will be much helpful to raise the issue here. now  I close the issue, if you find any other issue please feel free to submit.

**Comment by harryho** [comment]
I recommended the extension tool of react, redux for chrome, since it is not a back end node app or SSR app. I don't see the benefit there. I believe stackoverflow or Google will be much helpful to raise the issue here. now  I close the issue, if you find any other issue please feel free to submit.
