### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ERRLKing** [harryho/react-crm#3]
After a fresh install, I can see the login form but clicking login does nothing to the page and results in the following errors in the browser console:

```
auth.js?1ea2:62 GET http://localhost:5354/token 0 ()
auth.js?1ea2:80 Error:  TypeError: Failed to fetch
```

**Comment by harryho** [comment]
Hi, I created a fresh clone, and build, run as README's instructions, it looks good:

```
npm i 
npm run start 
```

Once the app launches successfully, you can test fake API via browser:
`http://localhost:5354/token`

You should be able see sth below: 

```
{
  "access_token": "fake-token-12345789-abcdefgh",
  "user": {
    "firstName": "Admin",
    "lastName": "",
    "email": "admin@test.com",
    "password": "password"
  }
}
```

If you still have problem, please explain how to replicate your issue in detail.
