### ISSUE TITLE
Encountering the error when compile

### ISSUE THREAD

**Issue by limaoheng** [harryho/react-crm#45]
The stack trace is like below:

.node-gyp/19.9.0/include/node/common.gypi", line 1
npm ERR!     nerate ',
npm ERR!             ^
npm ERR! SyntaxError: EOL while scanning string literal

I suspect it's to do with the node version. 

This is what has installed on my device:

node: v19.9.0
nom: 9.6.3

Any suggestions? 

Thanks.

**Comment by harryho** [comment]
Hello,
Please use node 12 or 14. You can install nvm ( https://github.com/nvm-sh/nvm ) to switch different version of node. I will update the README to address this problem. 
Cheers,
Harry
