### ISSUE TITLE
On windows it does not install correctly and does not run

### ISSUE THREAD

**Issue by FMALeap** [harryho/react-crm#8]
--this is for the install 
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\ProgramData\Anaconda3\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\ProgramData\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\react-crm-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Program Files\nodejs\react-crm-master\node_modules\node-sass
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN formsy-material-ui@0.6.0 requires a peer of material-ui@^0.17.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.1 requires a peer of webpack@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fma\AppData\Roaming\npm-cache\_logs\2020-04-01T15_15_41_385Z-debug.log

----this is for the run
ERROR in Cannot find module 'node-sass'
Require stack:
- C:\Program Files\nodejs\react-crm-master\node_modules\sass-loader\lib\loader.js
- C:\Program Files\nodejs\react-crm-master\node_modules\webpack-core\lib\NormalModuleMixin.js
- C:\Program Files\nodejs\react-crm-master\node_modules\webpack\lib\NormalModule.js
- C:\Program Files\nodejs\react-crm-master\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Program Files\nodejs\react-crm-master\node_modules\webpack\lib\Compiler.js
- C:\Program Files\nodejs\react-crm-master\node_modules\webpack\lib\webpack.js
- C:\Program Files\nodejs\react-crm-master\tools\srcServer.js
 @ ./~/flexboxgrid/css/flexboxgrid.css 4:14-152 13:2-17:4 14:20-158

**Comment by harryho** [comment]
@FMALeap  Unfortunately I have no windows machine in place, but I have my friend who tried on his windows laptop. He can replicate your issue. You might give a go to change the node-sass to version 4.12.0. 

On the other hand, you can try the new version. The project has been upgraded to TypeScript. If you want the ES6 version, please check out the branch mui-r15.
